[semver:major] Initial release
CircleCI-Public/microsoft-msix-orb pull request #1
Opened 2021-04-22 15:59 UTC by gmemstr

2021-04-29 21:02 UTC, KyleTryon requested changes

2021-04-29 21:02 UTC, KyleTryon commented on .circleci/config.yml
> +      shell: powershell.exe
Wouldnt the shell be set at the command level for the orb so the user isnt tasked with this?

2021-04-29 21:02 UTC, KyleTryon commented on .circleci/config.yml
> +          context: orb-publishing
The correct context name is: `orb-publisher`

2021-04-29 21:02 UTC, KyleTryon commented on src/commands/sign.yml
> +    default: "~/project"
Is this correct for windows?

2021-04-29 21:02 UTC, KyleTryon commented on src/@orb.yml
>    Sample orb description
Needs description

2021-04-29 21:02 UTC, KyleTryon commented on src/@orb.yml
>    home_url: "https://www.website.com/docs"
needs home url

2021-04-29 21:02 UTC, KyleTryon commented on sample/SampleProject/My Project/Resources.resx
> +    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
I assume it is fine, but is this key of any importance?

2021-04-29 21:02 UTC, KyleTryon commented on .circleci/config.yml
>            publish-version-tag: false
Enable tagging
  Add the ssh key with write access and the orb-publisher bot user.
enable PR commenting.
will slack confluence document.

2021-04-29 21:02 UTC, KyleTryon commented on .circleci/config.yml
> +          context: orb-publishing
^ propagate to other locations in the config.

2021-04-30 08:17 UTC, gmemstr commented on .circleci/config.yml
> +      shell: powershell.exe
Completely forgot this could be set at the step level.

2021-04-30 08:38 UTC, gmemstr commented on sample/SampleProject/My Project/Resources.resx
> +    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
Not that I'm aware of.

2021-04-30 08:39 UTC, gmemstr commented on src/commands/sign.yml
> +    default: "~/project"
PowerShell does support it, although `cmd` does not :)

2021-04-30 13:30 UTC, KyleTryon approved these changes
Looking good 👍

2021-04-30 13:39 UTC, merged